# Generated by Django 5.0.7 on 2024-07-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_detalle', to='autos.auto')),
            ],
        ),
    ]
