# Generated by Django 5.0.7 on 2024-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='nombre',
            field=models.CharField(default='Auto por defecto', max_length=255),
        ),
    ]
