# Generated by Django 5.0.7 on 2024-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_imagen_auto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagenprev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
